baseURL = "http://nabilmh.com"
languageCode = "en-us"
paginate = 5

title = "Nabil Mosharraf Hossain"
theme = "papermodx"  # The name of the theme you're using

googleAnalytics = "G-0Z1CB301MH"

[minify]
disableXML = true
minifyOutput = true

# [params.cover]
# hidden = true
# hiddenInList = true
# hiddenInSingle = true

# [params.fuseOpts]
# isCaseSensitive = false
# shouldSort = true
# location = 0
# distance = 1_000
# threshold = 0.4
# minMatchCharLength = 0
# keys = [ "title", "permalink", "summary", "content" ]

 [[menu.main]]
identifier = "archive"
 name = "Past"
 url = "archives"
 weight = 10

 [[menu.main]]
 identifier = "tags"
 name = "Topics"
 url = "tags/"
 weight = 20

 [[menu.main]]
 identifier = "about"
 name = "About"
 url = "about/"
 weight = 30

# [[menu.main]]
# identifier = "example"
# name = "example.org"
# url = "https://example.org"
# weight = 30


  [taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"



[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"

keywords = [ "Blog", "Portfolio", "PaperModX" ]
author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"

ShowToc = true

TocSide = 'right'  # or 'right'

defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false

comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

 [[params.socialIcons]]
 name = "github"
 url = "https://github.com/nabil6391"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/nabil6391/"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@techtalkwithnabil"

    [[params.socialIcons]]
  name = "medium"
  url = "https://nabil6391.medium.com/"



images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there ğŸ‘‹"
  Content = """
**Senior Software Engineer** with 8+ years of experience. ğŸ“±
- Built 20+ apps, with one having 650k monthly users: [**Quran App**](https://gtaf.org/)
- Expertise in: 
  - Android (Java & Kotlin)
  - Flutter (Dart) ğŸš€
  - Frontend (Reactjs) & Backend (Node.js, Golang) ğŸ› ï¸
- Authored ğŸ“š:
  - [**Graphview Flutter Library**](https://pub.dev/packages/graphview)
  - [**LottieSwipeRefreshLayout**](https://github.com/nabil6391/LottieSwipeRefreshLayout)
- Writings âœ’ï¸: [**Medium**](https://nabil6391.medium.com/)
- Video: [**Youtube**](https://www.youtube.com/@techtalkwithnabil) 
- Keen on AI ğŸ¤–, especially speech-to-text and face detection.
- Passionate about product development ğŸš€, data analysis ğŸ“Š, and leadership ğŸ–ï¸.
"""
